### ISSUE TITLE
Underflow subtraction

### ISSUE THREAD

**Issue by ktmattson-alion** [sdd-org/kiddo#172] opened 2024-05-21 18:07 UTC
I have at least one point cloud (so far each one I've tried) that causes `calc_pivot` to underflow [here](https://github.com/sdd/kiddo/blob/965121229a7d580fd79608b0c8c40b7daae68133/src/immutable/float/kdtree.rs#L553). Unfortunately I'm not able to release them (plus they are very large,) so I'll try to characterize the problem as it occurs.

When we get a panic, `chunk_length` =  65 and `shifted` = 64. Thus, `pivot` = (65 + 64) >> 1 = 64. There is a catch for `chunk_length` being odd, but it fails to engage because `shifted` != 0.

Looking over this function, I see a series of conditions, but there are only two outcomes: `pivot` = `pivot.next_power_of_two()` or `(pivot + 1).next_power_of_two()`.  And while there is a test on `stem_index`, it doesn't actually alter the logic: odd numbers need to be incremented after shifting to get the correct next power.

I tried this modification,
```
let mut pivot = chunk_length + shifted;  
 pivot = if pivot & 1 == 1 {  
   ((pivot >> 1) + 1).next_power_of_two()  
} else {  
    (pivot >> 1).next_power_of_two()  
};  
pivot -= shifted;  
```
but it still fails for values like chunk = 42, shifted = 75. At this point, I don't really understand quite what is supposed to happen. Like I can stabilize this function naively, with checked subtraction, but what's supposed to happen when shifted > pivot? plus later on there's another underflow problem if pivot > chunk_length.

**Comment by HenrikJStromberg** [comment] 2024-09-26 13:29
I have the same issue with a point cloud of about 4k points which I am able to share. For me the issue arises when using the ImmutableKdTree.
[points.csv](https://github.com/user-attachments/files/17149206/points.csv)

The same issue can be reproduced by loading a 3d point cloud of zeros with 33 or more points into ImmutableKdTree:
```
    #[test]
    fn reproduction(){
        let end = 33;
        let mut tree_entries = Vec::with_capacity(end);
        for i in 0..end {
            let mut point = [0f64; 3];
            for j in 0..3 {
                point[j] = 0.;
            }
            tree_entries.push(point);
        }
        let a =ImmutableKdTree::new_from_slice(&tree_entries);
        assert_eq!(a.size(), end);
    }
```

**Comment by sdd** [comment] 2024-10-01 20:52
Hi Both. Thanks for the input here, much appreciated. I've got a variant of the ImmutableTree that I'm working on that is more resilient - rather than strictly cycling through the dimensions in sequence, it defaults to that but is able to change the split dimension of a given node if construction fails due to all the points in a bucket having the same value on the split plane axis (the root cause of these construction failures).

@HenrikJStromberg unfortunately even this change would still fail for a tree with a bucket size of 32 having 33 all-zero points added to it - this is a fundamental limitation of having a fixed bucket size and will never work for any of kiddo's fixed bucket size trees. I have another design for a hybrid tree that uses the default and higher-performance fixed bucket approach but also has the capability to fall back to dynamic sized buckets at the individual bucket level when this kind of situation is encountered. This is more complex to implement and may impact performance to some extent - we'll see how much once the work on it is complete.

**Comment by HenrikJStromberg** [comment] 2024-10-03 05:49
I understand, that the all zero example is a wird corner case. I got to it as I was trying to reproduce the bug I got on the uploaded data with a more simple problem. The points in my csv file however are unique, so I think exploring the cause of failure for it might be more insightful. I have only mentally linked the situations as they cause the came exception.

**Comment by sdd** [comment] 2024-10-03 22:30
Thanks Henrik. The CSV file was very useful. I've been experimenting with a variation on the ImmutableKdTree that can dynamically vary the split dimension at each node, rather than strictly cycling through the dimensions in order every time.

This uses slightly more space to store the dimension used for each split plane as a u8 (limiting the use of this to 256 dimensions - not a problem in this case!). This has the advantage of making construction much quicker, as switching dimensions when non-ideal situations are encountered is much faster do do than the complex rebalancing logic that was in place before.

I added an example script that reads in your points.CSV and successfully builds a tree with this new approach, succeeding in 400 microseconds on my machine.

This approach does not work in every scenario - I also have another example that uses an example 2.5 million point LAS pointcloud file that I found online of a desk, and construction fails for this.

I think it may be possible to combine the dynamic split dimension approach with the rebalancing approach to allow construction to succeed in more cases than either alone (although never in your pathological 33-all-zero-points example 😅 )

The branch is available here: https://github.com/sdd/kiddo/tree/feat/dynamic-split-dimension
With the example I mentioned based on your CSV here: https://github.com/sdd/kiddo/blob/feat/dynamic-split-dimension/examples/pointcloud-csv.rs

I'll carry on developing this approach over the coming days, with the aim of the result being released in an upcoming v5 release.

**Comment by sdd** [comment] 2024-12-04 20:58
This issue should be resolved in https://github.com/sdd/kiddo/pull/186 as part of the rewrite of the `ImmutableKdTree`, which was just released as Kiddo v5.0.0 🎉 

https://crates.io/crates/kiddo/5.0.0

I know this issue was raised a while ago, and you have probably moved on, but if you do get chance to try v5 I'd love to hear any feedback. I'm closing this issue.

**Closed as completed by sdd** 2024-12-04 20:58 UTC

**Comment by HenrikJStromberg** [comment] 2024-12-07 08:47
Thanks for the rewrite. As far as my use is concerned it works now.

**Comment by sdd** [comment] 2024-12-08 20:45
That's great to hear @HenrikJStromberg - thanks for letting me know!
